name:                haskellcrud
version:             0.1.0.0
github:              "githubuser/haskellcrud"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellcrud#readme>

dependencies:
- base == 4.*
- aeson >= 1.2
- servant
- servant-server
- servant-client
- wai >= 3.2
- warp >= 3.2
- bytestring >= 0.10
- resource-pool >= 0.2
- http-client >= 0.5
- text >= 1.2
- http-types >= 0.12
- postgresql-simple >= 0.5

library:
  source-dirs: src

executables:
  haskellcrud-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskellcrud

tests:
  haskellcrud-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - haskellcrud
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
